# Generated by Django 5.1.7 on 2025-03-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorystock',
            old_name='count',
            new_name='quantity',
        ),
    ]
